#!/usr/bin/env python3
"""Decides which models the proxy should offer, and keeps the model menu to the
current generation only.

The menu Claude Code shows is whatever the proxy serves, so trimming happens
here rather than in the client. Two rules do the work, and both are written in
terms of tier words and version numbers rather than model names, so a release
next month is handled without editing this file:

  1. Whole tiers we never want (cut-down variants, side models, generators)
     are dropped outright.
  2. Of everything that remains, only the newest version of each family
     survives -- one Opus, one Sonnet, one Gemini Pro, one Grok, and so on.

Versions are read from the display name, not the id: the proxy's ids are
deliberately disguised (a Gemini 3.5 model is served as "gemini-3-flash-agent"),
so ids cannot be trusted for ordering.

Modes:
  list   [--all]           print the catalogue, grouped by provider
  plan                     print the models that survive, one per line
  sync   CONFIG CATALOGUE  rewrite the proxy's exclusion list; print changed|same
  agents DIR               write one subagent per non-Claude provider
  clear  CONFIG            drop the exclusion list; print changed|same
  check  MODEL             exit 0 if the proxy can reach MODEL

Reads the proxy's model list (Anthropic shape) on stdin.

CATALOGUE is a remembered union of every model the proxy has ever reported.
It has to exist: excluding a model hides it from the proxy's own list, so
deriving the next exclusion list from the live list would let each run forget
what it hid last time, and the hidden models would come straight back.
"""

import json
import os
import re
import sys

CLOAK = "-dd-"

# Tiers that never belong in a coding session: cut-down variants, side models,
# and anything that generates media rather than text.
BLOCKED = re.compile(
    r"(?<![a-z])("
    r"mini|nano|lite|small|oss|spark|build|composer|preview|"
    r"low|fast|"
    r"image|video|imagine|audio|speech|voice|tts|whisper|embed|rerank"
    r")(?![a-z])"
    r"|auto.?review|non.?reasoning|multi.?agent",
    re.I,
)

# A family is a provider plus one of these tier words. Everything without a
# tier word is that provider's main line.
TIERS = ["opus", "sonnet", "haiku", "fable", "pro", "flash"]

PROVIDERS = [
    ("Claude", re.compile(r"claude", re.I)),
    ("ChatGPT", re.compile(r"(gpt|codex)", re.I)),
    ("Antigravity", re.compile(r"gemini", re.I)),
    ("Grok", re.compile(r"grok", re.I)),
    ("Kimi", re.compile(r"kimi", re.I)),
]

# owned_by value -> the proxy's name for that sign-in channel
CHANNELS = {
    "anthropic": "claude",
    "openai": "codex",
    "antigravity": "antigravity",
    "xai": "xai",
    "kimi": "kimi",
}

BLOCK_KEY = "oauth-excluded-models"

AGENT_TEMPLATE = """---
name: {slug}
description: Runs on {name} ({provider}) instead of Claude. Use ONLY when the user explicitly asks for {provider}, or asks for a second opinion from a different model. Requires a multi-model session.
model: {model}
---

You are running on {name}, reached through the user's local model proxy. You have
the same tools as any other subagent: read and edit files, run shell commands,
and search the repository.

Do the work you were asked to do and report the result plainly. If you were asked
for a second opinion, say where you agree and where you do not, and give your
reasoning rather than a verdict alone.

<!-- Generated by `ccx --agents`. Edits here are overwritten. -->
"""


def plain_id(mid):
    """The proxy disguises non-Claude ids by reversing them behind a prefix."""
    return mid.split(CLOAK, 1)[1][::-1] if CLOAK in mid else mid


def provider_of(text):
    for name, pat in PROVIDERS:
        if pat.search(text):
            return name
    return "Other"


def tier_of(name):
    low = name.lower()
    for t in TIERS:
        if re.search(r"(?<![a-z])%s(?![a-z])" % t, low):
            return t
    return "main"


def version_of(name):
    """First version-looking number in the display name.

    Read as a decimal on purpose: xAI's 4.20 comes before 4.6, and comparing
    the parts as whole numbers would put it after. Large numbers are parameter
    counts or date stamps, not versions, so they do not count.
    """
    m = re.search(r"(?<![\d.])(\d+(?:\.\d+)?)", name)
    if not m:
        return None
    v = float(m.group(1))
    return None if v >= 100 else v


def load():
    raw = json.load(sys.stdin)
    out = []
    for m in raw.get("data", []):
        mid = m.get("id")
        if not mid:
            continue
        name = m.get("display_name") or mid
        out.append(
            {
                "id": plain_id(mid),
                "name": name,
                "channel": CHANNELS.get(m.get("owned_by", ""), m.get("owned_by", "")),
                # Named off the display name only. The disguised ids all begin
                # with a Claude prefix, so reading them here would file every
                # provider's models under Claude and collapse the families
                # into one -- which silently drops whole providers.
                "provider": provider_of(name),
                "tier": tier_of(name),
                "version": version_of(name),
                # Each provider reports its own context size. Claude Code only
                # ships sizes for Anthropic models and assumes 200k for the
                # rest, which compacts sessions long before they are full.
                "window": m.get("max_input_tokens"),
            }
        )
    return out


def frontier(models):
    """Current generation only: drop blocked tiers, then keep the newest
    version of each family."""
    alive = [m for m in models if not BLOCKED.search(m["name"]) and m["version"] is not None]
    best = {}
    for m in alive:
        key = (m["provider"], m["tier"])
        if key not in best or m["version"] > best[key]:
            best[key] = m["version"]
    return [m for m in alive if m["version"] == best[(m["provider"], m["tier"])]]


def order(models):
    rank = {name: i for i, (name, _) in enumerate(PROVIDERS)}
    return sorted(models, key=lambda m: (rank.get(m["provider"], 99), m["tier"], m["name"]))


def render_block(dropped, channels):
    """Exclude every dropped id in every channel.

    A model can be served by more than one sign-in channel, and the proxy only
    ever lists one of them per id — so hiding it in the channel it happens to
    be listed under just makes the other channel's copy surface instead.
    Naming a model in a channel that never had it is harmless."""
    by_channel = {ch: {m["id"] for m in dropped} for ch in channels}
    lines = [
        "# Generated by ccx: keeps the model menu to the current generation.",
        "# Regenerate with `ccx --refresh`; hand edits here are overwritten.",
        BLOCK_KEY + ":",
    ]
    for ch in sorted(by_channel):
        lines.append("  %s:" % ch)
        for mid in sorted(by_channel[ch]):
            lines.append('    - "%s"' % mid)
    return "\n".join(lines) + "\n"


def strip_block(text):
    out, skipping = [], False
    for line in text.splitlines(keepends=True):
        if line.startswith(BLOCK_KEY + ":"):
            skipping = True
            continue
        if skipping:
            # the block ends at the next line that starts a new top-level key
            if line.strip() and not line[0].isspace():
                skipping = False
            else:
                continue
        if line.startswith("# Generated by ccx") or line.startswith("# Regenerate with `ccx"):
            continue
        out.append(line)
    return "".join(out).rstrip("\n") + "\n"


def slot(m):
    """The same model id can be served by more than one sign-in channel, under
    different display names. Excluding it in one channel leaves the other
    still offering it, so channel and id together identify a listing."""
    return (m["channel"], m["id"])


def remember(path, live):
    """Union the live list into the remembered catalogue and return it."""
    try:
        with open(path) as fh:
            known = {slot(m): m for m in json.load(fh)}
    except Exception:
        known = {}
    for m in live:
        known[slot(m)] = m
    with open(path, "w") as fh:
        json.dump(sorted(known.values(), key=lambda m: (m["channel"], m["id"])), fh, indent=1)
    return list(known.values())


def main():
    mode = sys.argv[1]

    if mode == "clear":
        path = sys.argv[2]
        with open(path) as fh:
            text = fh.read()
        stripped = strip_block(text)
        print("same" if stripped == text else "changed")
        if stripped != text:
            with open(path, "w") as fh:
                fh.write(stripped)
        return

    models = load()
    if not models:
        sys.stderr.write("no models -- nothing is logged in yet. Run:  ccx --login\n")
        sys.exit(2)

    keep = frontier(models)

    if mode == "check":
        wanted = sys.argv[2]
        if wanted in {m["id"] for m in models}:
            sys.exit(0)
        sys.stderr.write("the proxy cannot reach %r -- run  ccx --list\n" % wanted)
        sys.exit(2)

    if mode == "window":
        wanted = sys.argv[2]
        for m in models:
            if m["id"] == wanted and m["window"]:
                print(int(m["window"]))
                return
        return  # unknown: print nothing, and leave Claude Code to its own guess

    if mode == "list":
        show = models if "--all" in sys.argv else keep
        kept = {m["id"] for m in keep}
        current, seen = None, set()
        for m in order(show):
            if m["id"] in seen:      # same model offered by two channels
                continue
            seen.add(m["id"])
            if m["provider"] != current:
                current = m["provider"]
                print("\n" + current)
            mark = "" if m["id"] in kept else "   (hidden)"
            win = "  %dk ctx" % (m["window"] // 1000) if m["window"] else ""
            print("  %-30s %-28s%s%s" % (m["id"], m["name"], win, mark))
        if "--all" not in sys.argv:
            print("\n%d of %d shown; older versions are hidden. ccx --list --all for everything."
                  % (len(keep), len(models)))
        return

    if mode == "plan":
        for m in order(keep):
            print(m["id"])
        return

    if mode == "agents":
        # One subagent per non-Claude provider, pinned to that provider's
        # current model. Written from the live catalogue rather than kept as a
        # list, so they follow the menu when a new generation lands.
        target = sys.argv[2]
        os.makedirs(target, exist_ok=True)
        # Newest wins. A provider's fast tier often ships a generation ahead of
        # its heavy tier -- Gemini Flash 3.6 against Pro 3.1 -- and the newer
        # model is the one worth handing work to. Tier only breaks a tie.
        tier_pref = {"pro": 0, "opus": 0, "fable": 0, "main": 1, "sonnet": 1, "flash": 2, "haiku": 3}
        best = {}
        for m in sorted(keep, key=lambda m: (-(m["version"] or 0), tier_pref.get(m["tier"], 5), m["name"])):
            if m["provider"] in ("Claude", "Other"):
                continue
            best.setdefault(m["provider"], m)
        written = []
        for provider, m in best.items():
            slug = "ask-" + provider.lower()
            with open(os.path.join(target, slug + ".md"), "w") as fh:
                fh.write(AGENT_TEMPLATE.format(
                    slug=slug, provider=provider, model=m["id"], name=m["name"]))
            written.append("%s -> %s" % (slug, m["name"]))
        for line in written:
            print(line)
        return

    if mode == "sync":
        path, catalogue = sys.argv[2], sys.argv[3]
        # Decide against everything ever seen, not against what is visible now.
        everything = remember(catalogue, models)
        kept = {m["id"] for m in frontier(everything)}
        channels = sorted({m["channel"] for m in everything if m["channel"]})
        dropped = {m["id"]: m for m in everything if m["id"] not in kept}
        with open(path) as fh:
            text = fh.read()
        wanted = strip_block(text) + "\n" + render_block(dropped.values(), channels)
        if wanted == text:
            print("same")
            return
        with open(path, "w") as fh:
            fh.write(wanted)
        print("changed")
        return

    sys.stderr.write("unknown mode %r\n" % mode)
    sys.exit(2)


main()
